<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProductionRessource extends \Entities\ProductionRessource implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdProductionRessource()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idProductionRessource"];
        }
        $this->__load();
        return parent::getIdProductionRessource();
    }

    public function setIdBatimentFk($idBatimentFk)
    {
        $this->__load();
        return parent::setIdBatimentFk($idBatimentFk);
    }

    public function getIdBatimentFk()
    {
        $this->__load();
        return parent::getIdBatimentFk();
    }

    public function setIdRessourceFk($idRessourceFk)
    {
        $this->__load();
        return parent::setIdRessourceFk($idRessourceFk);
    }

    public function getIdRessourceFk()
    {
        $this->__load();
        return parent::getIdRessourceFk();
    }

    public function setProductionHeure($productionHeure)
    {
        $this->__load();
        return parent::setProductionHeure($productionHeure);
    }

    public function getProductionHeure()
    {
        $this->__load();
        return parent::getProductionHeure();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idProductionRessource', 'idBatimentFk', 'idRessourceFk', 'productionHeure');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}