<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Joueur extends \Entities\Joueur implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdJoueur()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idJoueur"];
        }
        $this->__load();
        return parent::getIdJoueur();
    }

    public function setPseudoJoueur($pseudoJoueur)
    {
        $this->__load();
        return parent::setPseudoJoueur($pseudoJoueur);
    }

    public function getPseudoJoueur()
    {
        $this->__load();
        return parent::getPseudoJoueur();
    }

    public function setEmailJoueur($emailJoueur)
    {
        $this->__load();
        return parent::setEmailJoueur($emailJoueur);
    }

    public function getEmailJoueur()
    {
        $this->__load();
        return parent::getEmailJoueur();
    }

    public function setMdpJoueur($mdpJoueur)
    {
        $this->__load();
        return parent::setMdpJoueur($mdpJoueur);
    }

    public function getMdpJoueur()
    {
        $this->__load();
        return parent::getMdpJoueur();
    }

    public function setIdRaceFk($idRaceFk)
    {
        $this->__load();
        return parent::setIdRaceFk($idRaceFk);
    }

    public function getIdRaceFk()
    {
        $this->__load();
        return parent::getIdRaceFk();
    }

    public function setDescriptionJoueur($descriptionJoueur)
    {
        $this->__load();
        return parent::setDescriptionJoueur($descriptionJoueur);
    }

    public function getDescriptionJoueur()
    {
        $this->__load();
        return parent::getDescriptionJoueur();
    }

    public function setSexeJoueur($sexeJoueur)
    {
        $this->__load();
        return parent::setSexeJoueur($sexeJoueur);
    }

    public function getSexeJoueur()
    {
        $this->__load();
        return parent::getSexeJoueur();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idJoueur', 'pseudoJoueur', 'emailJoueur', 'mdpJoueur', 'idRaceFk', 'descriptionJoueur', 'sexeJoueur');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}