<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class JoueurVille extends \Entities\JoueurVille implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdVille()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idVille"];
        }
        $this->__load();
        return parent::getIdVille();
    }

    public function setIdJoueurFk($idJoueurFk)
    {
        $this->__load();
        return parent::setIdJoueurFk($idJoueurFk);
    }

    public function getIdJoueurFk()
    {
        $this->__load();
        return parent::getIdJoueurFk();
    }

    public function setNomVille($nomVille)
    {
        $this->__load();
        return parent::setNomVille($nomVille);
    }

    public function getNomVille()
    {
        $this->__load();
        return parent::getNomVille();
    }

    public function setPositionxVille($positionxVille)
    {
        $this->__load();
        return parent::setPositionxVille($positionxVille);
    }

    public function getPositionxVille()
    {
        $this->__load();
        return parent::getPositionxVille();
    }

    public function setPositionyVille($positionyVille)
    {
        $this->__load();
        return parent::setPositionyVille($positionyVille);
    }

    public function getPositionyVille()
    {
        $this->__load();
        return parent::getPositionyVille();
    }

    public function setNombreBoisVille($nombreBoisVille)
    {
        $this->__load();
        return parent::setNombreBoisVille($nombreBoisVille);
    }

    public function getNombreBoisVille()
    {
        $this->__load();
        return parent::getNombreBoisVille();
    }

    public function setNombreFerVille($nombreFerVille)
    {
        $this->__load();
        return parent::setNombreFerVille($nombreFerVille);
    }

    public function getNombreFerVille()
    {
        $this->__load();
        return parent::getNombreFerVille();
    }

    public function setNombrePierreVille($nombrePierreVille)
    {
        $this->__load();
        return parent::setNombrePierreVille($nombrePierreVille);
    }

    public function getNombrePierreVille()
    {
        $this->__load();
        return parent::getNombrePierreVille();
    }

    public function setNombreNourritureVille($nombreNourritureVille)
    {
        $this->__load();
        return parent::setNombreNourritureVille($nombreNourritureVille);
    }

    public function getNombreNourritureVille()
    {
        $this->__load();
        return parent::getNombreNourritureVille();
    }

    public function setPopulationOccupeeVille($populationOccupeeVille)
    {
        $this->__load();
        return parent::setPopulationOccupeeVille($populationOccupeeVille);
    }

    public function getPopulationOccupeeVille()
    {
        $this->__load();
        return parent::getPopulationOccupeeVille();
    }

    public function setPopulationTotaleVille($populationTotaleVille)
    {
        $this->__load();
        return parent::setPopulationTotaleVille($populationTotaleVille);
    }

    public function getPopulationTotaleVille()
    {
        $this->__load();
        return parent::getPopulationTotaleVille();
    }

    public function setPopulationMaxVille($populationMaxVille)
    {
        $this->__load();
        return parent::setPopulationMaxVille($populationMaxVille);
    }

    public function getPopulationMaxVille()
    {
        $this->__load();
        return parent::getPopulationMaxVille();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idVille', 'idJoueurFk', 'nomVille', 'positionxVille', 'positionyVille', 'nombreBoisVille', 'nombreFerVille', 'nombrePierreVille', 'nombreNourritureVille', 'populationOccupeeVille', 'populationTotaleVille', 'populationMaxVille');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}