<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Message extends \Entities\Message implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdMessage()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idMessage"];
        }
        $this->__load();
        return parent::getIdMessage();
    }

    public function setDateMessage($dateMessage)
    {
        $this->__load();
        return parent::setDateMessage($dateMessage);
    }

    public function getDateMessage()
    {
        $this->__load();
        return parent::getDateMessage();
    }

    public function setIdExpediteurMessage($idExpediteurMessage)
    {
        $this->__load();
        return parent::setIdExpediteurMessage($idExpediteurMessage);
    }

    public function getIdExpediteurMessage()
    {
        $this->__load();
        return parent::getIdExpediteurMessage();
    }

    public function setObjetMessage($objetMessage)
    {
        $this->__load();
        return parent::setObjetMessage($objetMessage);
    }

    public function getObjetMessage()
    {
        $this->__load();
        return parent::getObjetMessage();
    }

    public function setTxtMessage($txtMessage)
    {
        $this->__load();
        return parent::setTxtMessage($txtMessage);
    }

    public function getTxtMessage()
    {
        $this->__load();
        return parent::getTxtMessage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idMessage', 'dateMessage', 'idExpediteurMessage', 'objetMessage', 'txtMessage');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}