<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Batiment extends \Entities\Batiment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdBatiment()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idBatiment"];
        }
        $this->__load();
        return parent::getIdBatiment();
    }

    public function setIdTypeBatimentFk($idTypeBatimentFk)
    {
        $this->__load();
        return parent::setIdTypeBatimentFk($idTypeBatimentFk);
    }

    public function getIdTypeBatimentFk()
    {
        $this->__load();
        return parent::getIdTypeBatimentFk();
    }

    public function setNiveauBatiment($niveauBatiment)
    {
        $this->__load();
        return parent::setNiveauBatiment($niveauBatiment);
    }

    public function getNiveauBatiment()
    {
        $this->__load();
        return parent::getNiveauBatiment();
    }

    public function setCoutBoisBatiment($coutBoisBatiment)
    {
        $this->__load();
        return parent::setCoutBoisBatiment($coutBoisBatiment);
    }

    public function getCoutBoisBatiment()
    {
        $this->__load();
        return parent::getCoutBoisBatiment();
    }

    public function setCoutFerBatiment($coutFerBatiment)
    {
        $this->__load();
        return parent::setCoutFerBatiment($coutFerBatiment);
    }

    public function getCoutFerBatiment()
    {
        $this->__load();
        return parent::getCoutFerBatiment();
    }

    public function setCoutPierreBatiment($coutPierreBatiment)
    {
        $this->__load();
        return parent::setCoutPierreBatiment($coutPierreBatiment);
    }

    public function getCoutPierreBatiment()
    {
        $this->__load();
        return parent::getCoutPierreBatiment();
    }

    public function setCoutNourritureBatiment($coutNourritureBatiment)
    {
        $this->__load();
        return parent::setCoutNourritureBatiment($coutNourritureBatiment);
    }

    public function getCoutNourritureBatiment()
    {
        $this->__load();
        return parent::getCoutNourritureBatiment();
    }

    public function setCoutVillageoisBatiment($coutVillageoisBatiment)
    {
        $this->__load();
        return parent::setCoutVillageoisBatiment($coutVillageoisBatiment);
    }

    public function getCoutVillageoisBatiment()
    {
        $this->__load();
        return parent::getCoutVillageoisBatiment();
    }

    public function setTempsConstructionBatiment($tempsConstructionBatiment)
    {
        $this->__load();
        return parent::setTempsConstructionBatiment($tempsConstructionBatiment);
    }

    public function getTempsConstructionBatiment()
    {
        $this->__load();
        return parent::getTempsConstructionBatiment();
    }

    public function setIdBatimentRequis($idBatimentRequis)
    {
        $this->__load();
        return parent::setIdBatimentRequis($idBatimentRequis);
    }

    public function getIdBatimentRequis()
    {
        $this->__load();
        return parent::getIdBatimentRequis();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idBatiment', 'idTypeBatimentFk', 'niveauBatiment', 'coutBoisBatiment', 'coutFerBatiment', 'coutPierreBatiment', 'coutNourritureBatiment', 'coutVillageoisBatiment', 'tempsConstructionBatiment', 'idBatimentRequis');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}